In [1]:
import numpy as np

In [2]:
lst = []
for i in range(1,31):
    lst.append(i)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [3]:
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
my_matrix = arr.reshape(6,5)
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
my_sum = 0
for i in range(5):
    my_sum = my_sum + my_matrix[i][i]
my_sum

65

In [6]:
row_sum = 0
for i in range(5):
    row_sum = row_sum + my_matrix[1][i]
row_sum

40

In [7]:
ones_matrix = np.ones((6,5))
ones_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
ones_matrix + my_matrix

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31.]])

In [9]:
arr_rand = np.random.randint(0, 1000, 900)
arr_rand_matrix = arr_rand.reshape(30,30)
arr_rand_matrix

array([[200, 423, 154, 522,   0, 291,  54, 464, 321, 616, 716, 472, 450,
        964, 851, 956, 793, 256, 942, 632, 874, 311, 230, 469, 141, 149,
        426, 633, 971, 251],
       [540,  99, 416, 996, 929, 771, 421, 325, 336, 428, 554,  41, 140,
        349, 705, 312, 660, 170, 128, 951, 646,   3, 744,  78, 890, 854,
        534, 869, 812, 536],
       [ 69, 895, 533, 336, 112, 108, 724, 571, 973, 212, 558, 188,  73,
        513, 833, 514, 600, 508, 114, 356,  10, 694, 895, 358, 627, 487,
        652, 338, 260, 588],
       [568, 530, 466, 959, 825, 171, 975, 623, 841, 113, 683, 767,  49,
        472, 407, 219, 903, 807, 101, 554, 776, 543, 140, 477, 554, 382,
         34, 107, 427, 286],
       [301, 158, 493, 747, 786, 553, 313, 164, 398, 939, 262, 989, 172,
         10, 829, 236, 255, 926, 160, 806, 389, 984, 911, 900, 474, 916,
        325, 651, 414, 717],
       [160, 326, 618, 495, 606, 769, 721, 881, 998, 742, 800, 736, 846,
        480, 509, 732, 582, 895, 783, 695, 541, 404,

In [10]:
for i in range(30):
    print ("the minimum number is {} and its index is {}".format(arr_rand_matrix[i].min(), arr_rand_matrix[i].argmin()))

the minimum number is 0 and its index is 4
the minimum number is 3 and its index is 21
the minimum number is 10 and its index is 20
the minimum number is 34 and its index is 26
the minimum number is 10 and its index is 13
the minimum number is 63 and its index is 29
the minimum number is 21 and its index is 22
the minimum number is 6 and its index is 0
the minimum number is 69 and its index is 27
the minimum number is 5 and its index is 8
the minimum number is 43 and its index is 5
the minimum number is 23 and its index is 27
the minimum number is 10 and its index is 22
the minimum number is 169 and its index is 8
the minimum number is 112 and its index is 9
the minimum number is 14 and its index is 27
the minimum number is 62 and its index is 11
the minimum number is 13 and its index is 23
the minimum number is 2 and its index is 13
the minimum number is 14 and its index is 27
the minimum number is 31 and its index is 18
the minimum number is 35 and its index is 0
the minimum number i

In [11]:
arr_rand_matrix[10:20, 10:20]

array([[762, 108, 948, 701, 106, 630, 548, 977, 888, 977],
       [806,  83, 232, 547, 652, 513, 822, 271,  30,  58],
       [645, 149, 358, 116, 757, 380, 923, 760, 517, 768],
       [754, 172, 995, 788, 481, 494, 519, 866, 328, 601],
       [446, 961, 998, 912, 311, 837, 261, 508, 701, 542],
       [167, 964, 966, 636, 155, 151, 107, 602, 566, 703],
       [885,  62, 880, 800, 240,  73, 496, 235,  75, 660],
       [418, 528, 689, 201, 282, 889, 655, 539, 421, 729],
       [189, 121, 722,   2, 366, 774, 631, 931, 857, 786],
       [405,  37, 718, 966, 921, 301, 306, 464, 844, 944]])

In [12]:
mean = np.mean(arr_rand_matrix)
median = np.median(arr_rand_matrix)
std = np.std(arr_rand_matrix)
print("The mean is {}, the median is {}, the std is {}".format(mean, median, std))

The mean is 508.1688888888889, the median is 508.0, the std is 291.68132978168126


In [13]:
arr1 = np.arange(0,20, 1.5)
arr1

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])